src/index.ts, test/deploy.ts
=> Fix tester

.eslintrc.js, .gitignore, .prettierrc.js, README.md, src/index.ts, src/metamask/addNetwork.ts, src/metamask/approve.ts, src/metamask/configrmTransaction.ts, src/metamask/importPk.ts, src/metamask/index.ts, src/metamask/lock.ts, src/metamask/sign.ts, src/metamask/switchAccount.ts, src/metamask/switchNetwork.ts, src/metamask/unlock.ts, src/metamaskDownloader.ts, test/contract/index.ts, test/deploy.ts, test/test.spec.ts, types/solc/index.d.ts
=> Code improvements

src/index.ts, src/metamask/addNetwork.ts, test/test.spec.ts
Fix `addNetwork` command
Closes #22
=> Fix add network

.github/workflows/cron.yml
Scheduling daily testing of Metamask release
Closes #29 
**TODO**: improve issue reporting
=> Create test scheduling

package.json, src/metamaskDownloader.ts
=> Fix rate limit crash

package.json, src/index.ts, src/metamask/addNetwork.ts, src/metamask/index.ts, src/metamask/switchNetwork.ts, test/test.spec.ts
=> Fix add and switch network

src/metamaskDownloader.ts
=> Fix rate limit handling

docs/API.md, src/index.ts, src/metamaskDownloader.ts
- implement custom download path param for metamask
- update docs
Closes #41
=> Metamask download location

.github/pull_request_template.md, README.md, docs/API.md, src/index.ts, src/jest/global.d.ts, src/jest/setup.ts, src/metamaskDownloader.ts, src/utils.ts, test/test.spec.ts
=> Force metamask version

.github/workflows/cron.yml, src/index.ts, test/test.spec.ts
=> Smarter issues

src/metamaskDownloader.ts
-  improve logging on request
Closes #43
=> improve request logging

.gitignore, README.md, package.json, src/index.ts, src/metamask/addToken.ts, src/metamask/getTokenBalance.ts, src/metamask/index.ts, test/test.spec.ts, yarn.lock
- Added function to import a specified token
- Added function to get balance of specified token from metamask
- Added functions
- Updated tests
Functions can be used like this:
`await metamask.addToken('0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa');`
`await metamask.getTokenBalance('ETH');`
Closes #70
Closes #72
=> Added functions to add specified token to metamask & get a specified token balance

src/metamask/importPk.ts
=> fix import PK

docs/JEST.md, jest-preset.js, src/index.ts, src/jest/config.ts, src/jest/global.ts, src/jest/setup.ts, src/types.ts
Fix issues with jest preset
partly covers #75 but need to do more research on how to so do it simpler for consuming
Closes #127
=> fix: jest config

src/metamask/addToken.ts
=> fix: import token flaky

.github/workflows/main.yml, package.json, src/helpers/actions.ts, src/index.ts, src/setup/index.ts, src/snap/install-utils.ts, src/snap/install.ts, src/snap/invokeSnap.ts, src/types.ts, test/basic.spec.ts, test/constant.ts, test/deploy.ts, test/flask/snaps.spec.ts, test/global_flask.ts, test/utils/utils.ts
=> feat: method to bootstrap snap env

package.json
=> chore: node engine requirements

package.json
=> chore: remove metamask dir

package.json, test/constant.ts, test/contract.spec.ts, test/contract/contractInfo.ts, test/deploy.ts, tsconfig.json, yarn.lock
=> chore: update web3

.github/workflows/main.yml
=> fix: viewport typo

.github/workflows/main.yml, package.json, src/index.ts, src/metamask/approve.ts, src/setup/setupMetaMask.ts, src/snap/acceptDialog.ts, src/snap/install.ts, src/snap/rejectDialog.ts, src/types.ts, test/constant.ts, test/contract.spec.ts, test/contract/contractInfo.ts, test/deploy.ts, test/flask/snaps.spec.ts, tsconfig.json, yarn.lock
Seems like I dropped few commits while rebasing. 
Closes #
=> fix: viewport size, timeouts

src/constants.ts, src/snap/install.ts
fix https://github.com/ChainSafe/dappeteer/issues/228
Closes #228 
cc @Lykhoyda @BeroBurny
=> fix: dappeteer dependency (#229)

src/snap/utils.ts
Increased timeout as running the tests using xvfb requires more time to render
Closes #
=> fix: increase timeout

src/setup/index.ts, src/setup/launch.ts, src/setup/playwright.ts, src/setup/puppeteer.ts, src/types.ts, test/global.ts, test/global_flask.ts
Set headless version true as a default parameter
Closes #
=> feat: set default headless mode

src/index.ts, src/setup/index.ts, tsconfig.json
=> fix: preserve comments in compiled files

.github/workflows/main-release.yml
To simplify the feedback loop, added this `workflow`
=> chore: release on master update

.github/workflows/main.yml, package.json, scripts/download_metamask.ts, src/setup/utils/metaMaskDownloader.ts
=> chore: cache metamask version

.github/workflows/main.yml
=> chore: hide chore

README.md, src/setup/index.ts
=> fix: bootstrap launching with `userDataDir`

.github/workflows/pr.yaml
=> chore: update `Semantic PR`

.github/workflows/main-release.yml
=> chore: fix main release

README.md, docs/API.md, docs/BROWSER.md
=> chore: fix typos

package.json
=> fix: missing files in released package

package.json
=> fix: `peerDependenciesMeta` typo

package.json
=> fix: `peerDependencies` for `puppeteer`

.github/workflows/main-release.yml, .github/workflows/main.yml
https://yarnpkg.com/getting-started/migration#renamed
https://yarnpkg.com/cli/npm/publish
=> chore: fix `main.yml` release

.github/workflows/main.yml
=> fix: package publish

src/constants.ts, src/helpers/actions.ts, src/setup/setupActions.ts
=> feat: support MetaMask v10.31.0

.github/workflows/main.yml, src/setup/setupActions.ts
- Retry failing test during Github actions run
- fix flaky test
=> chore: add test retry
